In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data/ct_rate/dataset/radiology_text_reports/validation_reports.csv")
df.head()

,VolumeName,ClinicalInformation_EN,Technique_EN,Findings_EN,Impressions_EN
0,valid_1_a_1.nii.gz,Not given.,Non-contrast images were taken in the axial pl...,"Trachea, both main bronchi are open. Mediastin...",A few millimetric nonspecific nodules and sli...
1,valid_1_a_2.nii.gz,Not given.,Non-contrast images were taken in the axial pl...,"Trachea, both main bronchi are open. Mediastin...",A few millimetric nonspecific nodules and sli...
2,valid_2_a_1.nii.gz,Not given.,1.5 mm thick non-contrast sections were taken ...,As far as can be seen; A stable soft tissue m...,Metastatic breast ca. Multiple parenchymal n...
3,valid_2_a_2.nii.gz,Not given.,1.5 mm thick non-contrast sections were taken ...,As far as can be seen; A stable soft tissue m...,Metastatic breast ca. Multiple parenchymal n...
4,valid_3_a_1.nii.gz,Not given.,Non-contrast images were taken in the axial pl...,Trachea was in the midline of both main bronch...,Hiatal hernia. Appearance in both lungs that m...

In [5]:
# combine Technique and Findings and Impressions into a single column
df["report"] = df["Technique_EN"] + " " + df["Findings_EN"] + " " + df["Impressions_EN"]
df.head()

,VolumeName,ClinicalInformation_EN,Technique_EN,Findings_EN,Impressions_EN,report
0,valid_1_a_1.nii.gz,Not given.,Non-contrast images were taken in the axial pl...,"Trachea, both main bronchi are open. Mediastin...",A few millimetric nonspecific nodules and sli...,Non-contrast images were taken in the axial pl...
1,valid_1_a_2.nii.gz,Not given.,Non-contrast images were taken in the axial pl...,"Trachea, both main bronchi are open. Mediastin...",A few millimetric nonspecific nodules and sli...,Non-contrast images were taken in the axial pl...
2,valid_2_a_1.nii.gz,Not given.,1.5 mm thick non-contrast sections were taken ...,As far as can be seen; A stable soft tissue m...,Metastatic breast ca. Multiple parenchymal n...,1.5 mm thick non-contrast sections were taken ...
3,valid_2_a_2.nii.gz,Not given.,1.5 mm thick non-contrast sections were taken ...,As far as can be seen; A stable soft tissue m...,Metastatic breast ca. Multiple parenchymal n...,1.5 mm thick non-contrast sections were taken ...
4,valid_3_a_1.nii.gz,Not given.,Non-contrast images were taken in the axial pl...,Trachea was in the midline of both main bronch...,Hiatal hernia. Appearance in both lungs that m...,Non-contrast images were taken in the axial pl...

In [6]:
df[["report"]].to_csv("data/ct_rate/dataset/radiology_text_reports/validation_reports_combined.csv", index=False)